# Generated by Django 6.0.1 on 2026-02-02 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Enter your full name or a display name.', max_length=150, validators=[django.core.validators.RegexValidator(regex="^[\\w\\s.\\'-]+$")]),
        ),
    ]
