# Generated by Django 6.0.1 on 2026-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='journal_audio/'),
        ),
        migrations.AddField(
            model_name='journal',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
